### ISSUE TITLE
Stop timer when capture completed

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-elm#26]
At the moment it is possible to complete a capture while a timer is running:
![timer-capture-completed](https://user-images.githubusercontent.com/6057298/77676912-e23a6500-6f86-11ea-8e15-02a5d0d71f81.gif)

We can either:
- not allowing a capture to be checked when a timer is running
- stoping the running timer when the capture is checked

**Comment by iteles** [comment]
Personally, I feel like the second item is more intuitive.

If I'm marking something as complete, then I'm now no longer working on it.
Having to stop the timer and then mark as completed adds unnecessary steps! This should also be an option (stopping the timer and then marking as completed) of course but I would suggest that stopping the timer when an item is marked as complete should be the natural course.

**Comment by SimonLab** [comment]
The timer is now stopped if the capture is in progress before changing the capture to "completed"
![stop-timer-complete](https://user-images.githubusercontent.com/6057298/77750697-2e83b480-701c-11ea-85df-a9c7b2782b5d.gif)

**Comment by nelsonic** [comment]
Looks great @SimonLab 🎉
