### ISSUE TITLE
Redirect app to capture page on login (multipe tabs open)

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-elm#45]
When multiple pages of the application are open (e.g. different pages open on multiple browser tabs) the user is redirected to the login page if one one the page trigger a logout.

This is done with the subscription on each page, for example on the capture page we have the following code:

https://github.com/dwyl/app-mvp-elm/blob/0fe2775c41d5a1ee4c16fb2d781127876daab721/src/Pages/Capture.elm#L285-L290

And the `GotSession` message update the application with:
https://github.com/dwyl/app-mvp-elm/blob/0fe2775c41d5a1ee4c16fb2d781127876daab721/src/Pages/Capture.elm#L120-L123

We can see that the application will redirect to the home page. This work well on logout however on login we want the application to redirect to the capture page

**Comment by SimonLab** [comment]
We can check the type of the new session with the `isGuest` function (at the moment we have only 2 types of session `guest` and `session` ie loggedin)

```elm
            if Session.isGuest session then
                ( session
               -- if guest redirect to login page
                , Route.replaceUrl (Session.navKey session) Route.Login
                )
            else
                ( session
                -- if new session, redirect to the capture page
                , Route.replaceUrl (Session.navKey session) Route.Capture
                )
```

![login-logout](https://user-images.githubusercontent.com/6057298/78682120-82787e00-78e5-11ea-8a85-8f5e2768f294.gif)

**Comment by nelsonic** [comment]
@SimonLab looks great. 👍
